const SOURCES = [
  { source: "NCH", url: "https://nch.org.in/news", category: "Regulation" },
  { source: "NIH", url: "https://nih.ayush.gov.in/notice-board", category: "Education" },
  { source: "CCRH", url: "https://www.ccrhindia.ayush.gov.in/NewsandUpdates", category: "Research" },
  { source: "WHO", url: "https://www.who.int/initiatives/who-global-traditional-medicine-centre/", category: "International" },
];
const fallback = [
  {id:"nih-bhms-2026-27",source:"NIH",date:"16 Sep 2026",category:"Education",title:"Prospectus for BHMS 2026–27 released",summary:"NIH has published the prospectus for the 5½-year BHMS degree course, 38th batch, session 2026–27.",meaning:"This is an official education update relevant to BHMS applicants and counselling planning.",action:"Review the official prospectus and counselling notice before making admission or document decisions.",url:"https://nih.ayush.gov.in/notice-board"},
  {id:"ccrh-stsh-2026",source:"CCRH",date:"Sep 2026",category:"Research",title:"STSH 2026 updates and research opportunities",summary:"CCRH is publishing updates around the Short Term Studentship in Homoeopathy (STSH) 2026 and related research activity.",meaning:"The update signals current student-oriented research opportunities and deadlines within the official research ecosystem.",action:"If relevant, review the official STSH notice and keep the deadline/report requirements on your study or clinic learning calendar.",url:"https://www.ccrhindia.ayush.gov.in/NewsandUpdates"},
  {id:"nch-regulations",source:"NCH",date:"2026",category:"Regulation",title:"NCH notices and regulations continue to update",summary:"NCH is publishing current notices and regulatory material covering education, professional conduct, medical research and related matters.",meaning:"Clinic and professional workflows should be checked against the current official regulatory position rather than older guidance.",action:"Use the NCH news/regulations pages as the primary source before changing compliance or professional processes.",url:"https://nch.org.in/news"},
  {id:"who-tm",source:"WHO",date:"2026",category:"International",title:"WHO Global Traditional Medicine Centre updates",summary:"WHO continues work on research, evidence, quality, safety and international cooperation in traditional, complementary and integrative medicine.",meaning:"International TCIM developments are useful context, but they should not be treated as proof for any individual therapy.",action:"Use WHO updates for broader evidence and policy context, then review the underlying research before drawing clinical conclusions.",url:"https://www.who.int/initiatives/who-global-traditional-medicine-centre/"}
];
export default async function handler(req,res){
  const live=[];
  await Promise.all(SOURCES.map(async s=>{try{const r=await fetch(s.url,{headers:{"User-Agent":"HomeoCure-Intelligence/1.0"}});if(!r.ok)return;const html=await r.text();const clean=html.replace(/<script[\\s\\S]*?<\\/script>/gi," ").replace(/<style[\\s\\S]*?<\\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/\\s+/g," ").trim();const m=clean.match(/(?:News and Updates|Notice Board)[^]{0,500}?([A-Z][^]{20,140}?)(?=\\d{2}-\\d{2}-2026|\\d{2}\\s+Sep)/i);if(m)live.push({id:s.source.toLowerCase()+"-live",source:s.source,date:new Date().toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}),category:s.category,title:m[1].replace(/\\s+/g," ").trim(),summary:"Fresh item detected from the official source page. Open the source for the complete notice or article.",meaning:"This is source-level information; the dashboard does not infer clinical efficacy from a headline.",action:"Open the original source and review the complete document before acting.",url:s.url});}catch{}}));
  const byKey=new Map();[...live,...fallback].forEach(i=>{if(!byKey.has(i.id))byKey.set(i.id,i)});res.setHeader("Cache-Control","s-maxage=900, stale-while-revalidate=3600");return res.status(200).json({updated_at:new Date().toISOString(),items:[...byKey.values()].slice(0,12),sources:SOURCES});
}
